#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Ryo Kozuka ryokozu.fm710@sf7.so-net.ne.jp
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
c = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
if (ans % 2) == 0:
    c = 2
    print("偶数")
else:
    c = 1
    print("奇数")

